# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

-  bash: sudo bash install-az-cli.sh
   displayName: 'azure-cli'


- task: AzureCLI@1
  inputs:
    azureSubscription: 'Free Trial (8c6de12e-4b49-41c0-8eff-35ac89686cf4)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name bhai-rg2 --location westus --subscription 8c6de12e-4b49-41c0-8eff-35ac89686cf4'
    addSpnToEnvironment: true

- task: AzureCLI@2
  inputs:
     azureSubscription: 'Free Trial (8c6de12e-4b49-41c0-8eff-35ac89686cf4)'
     scriptLocation: 'scriptPath'
     scriptPath: 'Bapubhai/Test-Azure-PL-1/az-sub.sh'
     addSpnToEnvironment: true