# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

-  bash: sudo bash install-az-cli.sh
   displayName: 'azure-cli'

- task: AzureCLI@1
  inputs:
    scriptLocation: 'scriptPath'
    scriptPath: 'Bapubhai/Test-Azure-PL-1/az-sub.sh'
    workingDirectory: 'Bapubhai/Test-Azure-PL-1'
